### ISSUE TITLE
Button position is off

### ISSUE THREAD

**Issue by getsetbro** [jcreamer898/espresso#1]
For me, the button is above the code and hides before I can click it.
![issue1](https://f.cloud.github.com/assets/442793/1083922/36f82400-15a3-11e3-8008-d867bf8210cf.png)

**Comment by jcreamer898** [comment]
Thanks, I'll take a look!

**Comment by getsetbro** [comment]
Here is an alternative:
{
position: relative;
left: 100%;
margin-left: -82px;
margin-bottom: -23px;
}
